api/github.ts
http/getAxiosConfig.ts
http/index.ts

This is the first step towards allowing the CLI to set a user-agent (or similar) header on the requests to make it easier for us to debug user CLI issues.

Allow setting custom headers on the requests

---

lang/en.json

This PR only adjusts the strings for accounts, will link related PR for hubspot-cli once that is up. 
Will post screenshots in hubspot-cli PR
@shannon-lichtenwalter

Standardize account names

---

lib/cms/watch.ts

Reported on internal slack - looks like the watch command broke during the initial `local-dev-lib` migration and began crashing when validation errors occurred. This updates the command to allow passing in a `onUploadFileError` callback to log out these errors rather than throw for them.

Fix watch command errors

---

lib/__tests__/notify.ts
types/FileManager.ts

The BE team is removing this field. We don't use it anywhere in our lib or in consuming packages so it's safe to remove.
Note: Prettier was angry with me about the notify.ts file and that's why there are changes in there. I'm on the latest main branch, so I'm not sure what's going on there.
N/A
I'll ping the BE team internally to let them know about this

Remove the meta.charset_guess type

---

api/projects.ts

We need to edit the endpoint to check the status of cloning apps, so that it returns correct error messages. 
New beautiful error messages returned:

Refactor app clone status endpoint

---

http/index.ts

We need to have the full response from Axios for a use-case internally where we need to pull headers off of the incoming request.

Allow asking for full response from http methods

---

lib/personalAccessKey.ts

Adds a method that grabs the scopes on an access token for a given account.

Add a method to get available scopes on pak 

---

api/projects.ts

Reverts HubSpot/hubspot-local-dev-lib#173

Revert "Update some endpoints to point towards new project's service routes"

---

api/appsDev.ts
types/Apps.ts

I do not know how to spell but I am doing my best to learn and improve

Typo fix: PublicAppInstallCounts

---

api/projects.ts

Same as https://github.com/HubSpot/hubspot-local-dev-lib/pull/173 but with corrected path.
@brandenrodgers -> please test
cc @ypzheng

Corrected - New Project Service Paths

---

lib/personalAccessKey.ts

Add a option to force a token to refresh.
@kemmerle @camden11 @brandenrodgers

feat: Add a method to force a token refresh

---

api/github.ts

Adds a fallback to using env variables for the github auth token

chore: Add a fallback to process.env.GITHUB_TOKEN

---

lib/portManager.ts

Expose the `isPortManager` running function to be used in the `hs doctor` command

chore: Expose the isPortManagerRunning function

---

lib/cms/modules.ts
types/Modules.ts

Closes HubSpot/hubspot-cli-issues/issues/#344
https://git.hubteam.com/HubSpot/hubspot-cli-issues/issues/344

Consume is_available_for_new_content value from cli prompt

---

api/hubdb.ts
types/Hubdb.ts

Just a quick little function that pulls the published tables from the HubDB.
I'll make a pull request to add a `hs hubdb list` command in the CLI as well.
@brandenrodgers @joe-yeager @ajlaporte

Add a List Tables to HubDB (Another pull request will be made to the HubSpot CLI as well)

---

.github/workflows/unreleasedChangesCheck.yml

Add a check for unreleased changes to the LDL
@brandenrodgers @camden11 @kemmerle

chore: Add unreleased changes check action

---

scripts/release.ts

Brings the changes from this CLI PR to LDL.
https://github.com/HubSpot/hubspot-cli/pull/1238

Fix bug with updating next tag on releases to latest

---

scripts/release.ts

This was changed to `EXPERIMENTAL` so I could test it and I forgot to change it back
@brandenrodgers @joe-yeager

Update next tag for latest releases, not experimental

---

config/CLIConfiguration.ts
config/__tests__/CLIConfiguration.test.ts
types/Config.ts

We have a type for `Mode`, but I noticed in @kemmerle 's recent PR that we're not actually using it everywhere.

chore: Update config mode to Mode type

---

lib/personalAccessKey.ts
types/Accounts.ts

Ran `prettier:write` to make sure formatting is correct

prettier makes it prettier

---

scripts/release.ts

Don't create or push git tags for experimental releases

chore: Tagless experimental releases

---

config/configFile.ts
config/index.ts
config/migrate.ts
constants/config.ts
lang/en.json
package.json

This PR adds util functions for the new `hs config migrate` command. 
See https://github.com/HubSpot/hubspot-cli/pull/1398

Support `hs config migrate` command

---

api/fireAlarm.ts
types/FireAlarm.ts

a basic fire alarm api util to support this CLI PR:  https://github.com/HubSpot/hubspot-cli/pull/1428

Add fire alarm api util

---

types/FireAlarm.ts

Just adding a new field that I want to be able to use in the CLI. It'll give us more granularity for targeting

Add urlRegexPattern to the fire alarm type

---

api/__tests__/projects.test.ts
api/projects.ts
package.json
types/Migration.ts
types/Project.ts

Updates the types as needed to account for the new APIs

chore: Update to async endpoints

---

models/HubSpotHttpError.ts

Add the `correlationId` to the debug output for HubSpotHttpErrors

chore: Add correlationId to the HubSpotHttpError

---

api/localDevAuth.ts
http/index.ts
package.json

Add the ability to debug log all of the network requests

feat: Add the ability to debug log all the network requests

---

types/DesignManager.ts

Updating the response type for the lighthouse score. It includes a "total" that we need to use in the CLI.

Fix lighthouse score response type

---

config/CLIConfiguration.ts
config/config_DEPRECATED.ts
config/index.ts
types/Config.ts

This adds a new field to the config that will let users opt into CLI auto updates. Eventually we'll default this to true, but the safest way to roll this out and test it is by making it opt-in.

Support auto update config field

---

api/__tests__/projects.test.ts
api/projects.ts

Supporting the ability to forcefully deploy a project build and ignore warnings.
cc/ @m-roll

Support force args for project deploy api

---

.github/CODEOWNERS

chore: Add Liam to CODEOWNERS

---

api/developerTestAccounts.ts

This will be used in the `hs test-account create` command. The gate sync takes a little bit of time. We want to show a loading spinner at the end of the create command to show that things are still happening. The test account won't operate correctly until all the gates are synced over. For example, the project upload might fail.

Add polling function for test account gate sync

---

api/developerTestAccounts.ts
types/developerTestAccounts.ts

Supporting the new app install endpoints. These support installing oauth apps into dev test accounts.
Details here: https://tools.hubteamqa.com/api-catalog/services/DeveloperTestPortalsService/v3/spec/internal

Support app install endpoints

---

api/developerTestAccounts.ts
types/developerTestAccounts.ts

Support ability to generate a pak for a test account from the parent account.

Support generate pak api for test accounts

---

types/developerTestAccounts.ts

Support free tier in type for accounts

Add free tier

---

package.json

Update version to v3.16.1-beta.0 for release

---

lang/en.json

Small spelling fix in `en.json`

Spelling Fix

---

types/Build.ts

Adds `platformVersion` to the Build type (to be used in `hs project list` command)

Add platform version to Build type
