HubSpot/hubspot-local-dev-lib

- errors/__tests__/apiErrors.ts
- errors/apiErrors.ts
During our latest bug bashes, folks were receiving generic errors while attempting the `hs project upload` command, particularly when their accounts had gating issues. 
With @joe-yeager's help (he gave me access to his account, so I could reproduce the error), I found that we were destructuring the error object incorrectly and therefore not passing the correct status code to the switch statement in the `getAxiosErrorWithContext` function. 
BEFORE (Yucky, generic error):
AFTER (Beautiful, descriptive error):
@joe-yeager @brandenrodgers
> Fix issue with generic errors being returned with gating errors

- api/sandboxSync.ts
- lib/sandboxes.ts
- types/Sandbox.ts
This PR replaces an endpoint that sandboxes was using to poll for sync updates with a much simpler and more performant one. No changes are needed in hubspot-cli as the data that [pollSyncTaskStatus](https://github.com/HubSpot/hubspot-cli/blob/main/packages/cli/lib/sandboxes.js#L265-L326) expects does not change with this endpoint swap. 
I've also gone ahead and cleaned up some types that were ported over in a slightly weird state. 
To run this locally, navigate to your local instance of `hubspot-local-dev-lib` and run `yarn run local-dev`. Then go into your local instance of `hubspot-cli` and run `yarn link @hubspot/local-dev-lib` to link the local version. You can now run `yarn hs sandbox sync` to verify that everything still works. There should be no changes to what is displayed. 
No …
> Update sandbox types, replace polling API endpoint

- api/projects.ts
This fixes a bug where the CLI would error for any project that contains forward slashes in the name. The upload and deploy would succeed, but the CLI would show an error because the request to fetch the logs was returning with a 404.
> Url encode project name in request

- jest.config.js
- setupTests.ts
- Adds a setup file that runs before the tests executre
- delete `process.env.HUBAPI_DOMAIN_OVERRIDE` so in the event a user has an `export HUBAPI_DOMAIN_OVERRIDE` in their shell profile the tests will not use that value
> chore: Add a setupFile, delete process.env.HUBAPI_DOMAIN_OVERRIDE before tests execute

- http/__tests__/index.ts
- http/getAxiosConfig.ts
- types/Utils.ts
We were getting `ENOMEM` errors from `axios` because it appears to have a [memory leak starting in](https://github.com/axios/axios/issues/5641) `1.4.0` and in versions as late as `1.6.8`. The leak is caused by event listeners not being closed when http calls complete.  A solution to fix or at least limit the impact is to set `keepAlive` to true and limit the number of sockets which causes `axios` to reuse the connections instead of creating new ones.  
As an aside, we **_might_** notice some minor performance benefits as well on request heavy operations because we will be reusing connections.
[More context on connection management](https://developer.mozilla.org/en-US/docs/Web/HTTP/Connection_management_in_HTTP_1.x)
Changes:
- Pass custom `http` and `https` agents to `axios`
- Set …
> fix: Add keepAlive to axios agent

- api/appsDev.ts
- types/Apps.ts
This adds functionality to hit a new endpoint that returns the number of installs a public app has in developer test account. We'll use this on the CLI to determine if an app has installs that _aren't_ on test accounts (see https://git.hubteam.com/HubSpot/hubspot-cli-issues/issues/571)
> Add function to hit test portal installs endpoint

- api/github.ts
- lib/__tests__/github.ts
- lib/github.ts
We discovered a bug with the `hs project create` command: image files were not being downloaded correctly. Images were being stored as strings and written in `utf8`. Now we store them as array buffers and write them out to a binary file. 
@sejal27 @brandenrodgers @camden11 @joe-yeager
> Fix issue with downloading images from GitHub repos

- config/__tests__/config.ts
- http/__tests__/index.ts
- jest.config.js
- lib/__tests__/customObjects.ts
- lib/__tests__/fileMapper.ts
- lib/__tests__/hubdb.ts
- lib/__tests__/personalAccessKey.ts
- lib/__tests__/templates.ts
- lib/__tests__/trackUsage.ts
- lib/__tests__/uploadFolder.ts
Jest sets [`clearMocks`](https://jestjs.io/docs/configuration#clearmocks-boolean) to false by default which means that unless mocks are explicitly cleared between test invocations, the mocks states are carried between tests. which can lead to having tests that aren't well isolated and depend on the tests that come before them.
@brandenrodgers @kemmerle @camden11
> chore: Set jest `clearMocks` to true.  Remove manual mock clear calls

- lib/path.ts
This PR moves/creates the functions `sanitizeFileName` and `isValidPath` to the hubspot-local-dev-lib library. I think this makes more sense, since these are reusable for any file or path. In particular, I decided to rename the `sanitizeFileName` function from `sanitizeProjectName` when moving it to `local-dev-lib`, because it makes it more readable and reusable in the future. We're basically treating the project name as a directory/file name.
There is a sister [PR](https://github.com/HubSpot/hubspot-cli/pull/1102) in cli-lib. 
To test, you'll need to follow the `yarn link` instructions in the README file to use a symlinked version of local-dev-lib. 
We sanitize the project name before inserting it in the default path, and we validate for invalid characters/reserved names for the …
> Add functions to sanitize file name and validate path (Sister PR in cli-lib)

- api/appsDev.ts
- types/Apps.ts
Chris C. added an endpoint that returns metadata for a single public app. He also added a new property, preventProjectMigrations, a boolean that returns true when the app is a marketplace app that has not been added to the Ecosystem Quality review whitelist. This ties in disabling project migrations directly with the allow-list, which better future proofs this command.
This PR has a sister [PR](https://github.com/HubSpot/hubspot-cli/pull/1111) in the CLI. See that description for full context.
@brandenrodgers @joe-yeager
> Add endpoint to fetch single public app metadata (Sister PR in HubSpot CLI)

- config/configFile.ts
- errors/__tests__/apiErrors.ts
- errors/__tests__/standardErrors.ts
- errors/apiErrors.ts
- errors/fileSystemErrors.ts
- errors/standardErrors.ts
- lib/archive.ts
- lib/cms/functions.ts
- lib/cms/handleFieldsJS.ts
- lib/customObjects.ts
- lib/developerTestAccounts.ts
- lib/fileManager.ts
- lib/fileMapper.ts
- lib/github.ts
- lib/gitignore.ts
- lib/hubdb.ts
- lib/notify.ts
- lib/oauth.ts
- lib/personalAccessKey.ts
- lib/sandboxes.ts
- models/HubSpotAuthError.ts
- models/OAuth2Manager.ts
**_This PR looks huge, but the big changes are localized to a couple of files that I tagged with comments, the rest are typescript changes, or updating tests._**
Updates functions that take errors as arguments to take type `unknown` and to type narrow the error to prevent the methods to require type assertions every time they are called.  
The reasoning behind this:
- The default type of the `error` in catch blocks is `unknown` and it is considered a bad practice to set it to anything other than `unknown`.  
- It required type assertions on every invocation and they are considered a bad practice because they are disabling the type system by us asserting we know the type with full certainty.  Because of this they give us a false sense of type security
@camden11 @brandenrodgers @kemmerle
> chore: Make error handlers accept unknown and clean up type assertions

- types/Http.ts
Axios allows for more than just a plain JSON object for `data` in the config - see https://axios-http.com/docs/req_config. We have a need to pass a string here, and the PR just opens up the type based on the documentation.
> Allow different types of for Data for axios request config

- package.json
This exports `getAxiosConfig` from `local-dev-lib`. This will make it easier to make un-authed requests to HubSpot APIs, which is not currently supported by the `http` module.
More context: https://hubspot.slack.com/archives/C076QV345ME/p1721328218238189
In the future, we should provide a way to make un-authed requests directly from the `http` module.
> Export getAxiosConfig from package

- api/appsDev.ts
- types/Apps.ts
This adds support for hitting the new `apps-dev/external/public/v3/{appId}/install-counts-without-test-portals` endpoint, which returns public app production installs without the 30 minute delay the endpoint we were previously using had. This will allow the CLI to give users more up to date info about whether or not their public apps have active installs
> Add API function to get public app install counts without delay

- http/__tests__/index.ts
- http/__tests__/unauthed.ts
- http/addQueryParams.ts
- http/getAxiosConfig.ts
- http/index.ts
- http/unauthed.ts
- types/Http.ts
This adds new methods for hitting hubspot endpoints that don't require auth. See thread for more details on this ask:
https://hubspot.slack.com/archives/C076QV345ME/p1721328218238189
Decided it would be easier to put this into the `next` branch due to the changes to `http`, even though it doesn't actually have any breaking changes.
I feel like there might be a better way to name these functions? I couldn't think of anything that I really liked though.
> Unauthed http option

- api/projects.ts
We have moved over a number of REST endpoints from the build service to the projects service in an attempt to separate out functionality. This PR updates a handful of those endpoints which have changed. Nothing about the endpoints has changed outside of the new routing, so request/responses should be exactly the same.
We will be maintaining the old REST endpoints on the build service for the time being but we will need to coordinate when we can deprecate those without impacting users with older CLI versions. We might be able to utilize what @m-roll made a few weeks ago using the cli version headers to block requests.
cc @brandenrodgers @ypzheng
> Update some endpoints to point towards new project's service routes

- models/HubSpotHttpError.ts
When `HubSpotHttpError.updateContext` is called, it should regenerate the error messages with the new context if possible.
> fix: Fix updateContext not updating the messages

- constants/extensions.ts
- lib/fileMapper.ts
Report in cms dev tooling channel from infra that elevate theme is silently erroring on `tsx, ts, jsx` files when trying to fetch the theme.
This just adds those to the allowlist when checking extensions (don't want to add them to the default allowlist since that runs for `hs watch` as well). Error message here already exists just doesn't get logged in this circumstance
> Fix fetch for themes with JSR modules

- models/HubSpotHttpError.ts
- models/__tests__/HubSpotHttpError.ts
- types/Error.ts
Fixes the error where we weren't logging out the required scopes.
Fixes errors with the payloads getting logged
@kemmerle @brandenrodgers @camden11
> fix: Logging fixes

- api/localDevAuth.ts
- types/Accounts.ts
This adds a new `fetchEnabledFeatures` function to the `localDevAuth` api module that we can use to check gates for an account.
See https://git.hubteam.com/HubSpot/hubspot-cli-issues/issues/590
> Add fetchEnabledFeatures

- lib/trackUsage.ts
This is for consistency between the authed and unauthed tracking events. I wasn't able to test this, but I'm fairly certain this is preventing our unauthed requests from sending correctly in some cases. The impact is that our tracking for successful runs of `hs init` isn't accurate
> fix: Return the tracking request when not authenticated 

- lang/en.json
- lib/trackUsage.ts
This is a hack to temporarily fix usage tracking when dev accounts are targeted. This will cause those events to track as unauthenticated, which means we'll lose out on some user info, but this is better than losing the events entirely.
> Fix: Temporary fix for tracking so we dont lose events

- api/__tests__/projects.test.ts
- lib/trackUsage.ts
- models/HubSpotHttpError.ts
- models/__tests__/HubSpotHttpError.ts
Apply the changes from this [PR](https://github.com/HubSpot/hubspot-local-dev-lib/pull/169/files) to the next branch
> fix: Fix next branch merge

- config/CLIConfiguration.ts
- config/__tests__/CLIConfiguration.test.ts
- config/__tests__/config.test.ts
- config/getAccountIdentifier.ts
- config/index.ts
- constants/config.ts
- lib/__tests__/oauth.test.ts
- lib/oauth.ts
- lib/personalAccessKey.ts
- models/OAuth2Manager.ts
- package.json
- utils/accounts.ts
**THIS PR WAS REVERTED in #203--this PR reverts the revert.**
We are updating our HubSpot CLI configuration file, so that it will be created the root directory in a hidden folder: `~/.hubspot-cli/config.yml`. This will encourage users to take advantage of the `init`, `auth`, and `accounts` commands to update their config and help prevent config-related bugs. 
We will also be supporting the old configuration, which means that power users will still be able to use nested configs for different projects.
Sister PR: https://github.com/HubSpot/hubspot-cli/pull/1123
For Sandra, how would we like to alert customers about the new config? Currently, I have a prompt that asks them whether they'd like to use the new vs. old, but I'm not sure that's the best solution.
`hs init` (with new config):
`hs …
> Revert "Revert "Merge pull request #172 from HubSpot/refactor-config""

- LICENSE
- package.json
- scripts/build.ts
- tsconfig.json
This adds a (very slightly) modified version of the build script from the CLI to local-dev-lib. It also adds a LICENSE file (which we didn't have before for some reason. If there was a good reason for that I can remove) and includes the LICENSE and readme as part of the build output.
Up next: add the release script
> Add build script to LDL

- package.json
- scripts/build.ts
- scripts/lib/build.ts
- scripts/release.ts
This ports the new release script that was recently added to the CLI to local-dev-lib. The release script here is more or less identical, but doesn't contain the additional confirmation prompt when publishing to latest without a beta release. (Beta releases likely won't be as useful as this is a library, but I didn't see any reason to remove the option).
This also includes the recent change to move the logic for `build` into its own file.
Like the CLI, we'll have to do a bit of work to get things in the proper state:
* Release to the experimental tag
* Release to the beta tag
* Add back in the check for local/beta tag sync (and potentially remove the default experimental version)
@brandenrodgers @joe-yeager @kemmerle
> Add release script

- scripts/release.ts
Now that we've made a beta release, the release script check for the local version being in sync with `next` will work. I also removed the experimental default value of `0.0.0` since I could see that doing more harm then good if anything weird happens with fetching the version tags
> Restore check for local and npm version sync in release script

- lib/portManager.ts
- utils/PortManagerServer.ts
Updates the portManager shutdown flow to call a health check endpoint before attempting to shutdown the server.
> fix: Update port manager shutdown flow

- package.json
- scripts/release.ts
This fixes one major bug and makes a few more improvements to the release script
* Previously, the script failed when attempting to update the `next` tag after releases to latest. This is due to a slight difference between how `npm dist-tag` runs within `spawn` and how it runs directly in a terminal. Explicity specifying a `--registry` fixes this.
* If the `dist-tag` command _does_ fail, the script no longer runs cleanup (since the release itself was successful) and provides instructions for manually updating the `next` tag and pushing to Github.
* Added a confirmation prompt when attempting to release changes to `latest` that haven't already been released to `next`
* Added a prompt for NPM one-time password so you don't have to open your browser. This password seems to work for both the …
> More release script improvements

- scripts/release.ts
The release script now opens your browser to create a new release on Github, but this isn't necessary for `next` and `experimental` releases
> Only prompt to create release for latest releases

- config/CLIConfiguration.ts
- config/__tests__/CLIConfiguration.test.ts
- config/configUtils.ts
- config/config_DEPRECATED.ts
- config/index.ts
- constants/files.ts
- lang/en.json
- lib/__tests__/watch.test.ts
- lib/cms/uploadFolder.ts
- lib/cms/watch.ts
- lib/fileMapper.ts
- package.json
- types/Accounts.ts
- types/Config.ts
- types/Files.ts
See https://git.hubteam.com/HubSpot/hubspot-cli-issues/issues/718
This updates all references to `mode` to `cmsPublishMode` and renames all related functions and variables. It also changes the `defaultMode` setting within `hubspot.config.yml` to `defaultCmsPublishMode`. Both the new and legacy config modules have been updated to be able to read configs with either `defaultMode` or `defaultCmsPublishMode`, but will now always  use `defaultCmsPublishMode` when making updates to config files.
Currently released on `v0.1.0-experimental.0`
Test thoroughly. Also might be worth updating the config unit tests to test the backwards compatibility functionality/
> chore!: Rename Mode to CmsPublishMode

- api/appsDev.ts
- api/customObjects.ts
- api/designManager.ts
- api/developerTestAccounts.ts
- api/fileManager.ts
- api/fileMapper.ts
- api/fileTransport.ts
- api/functions.ts
- api/github.ts
- api/hubdb.ts
- api/lighthouseScore.ts
- api/localDevAuth.ts
- api/marketplaceValidation.ts
- api/projects.ts
- api/sandboxHubs.ts
- api/sandboxSync.ts
- api/secrets.ts
- api/validateHubl.ts
- http/index.ts
- http/unauthed.ts
- lib/__tests__/validate.test.ts
- types/Http.ts
Wraps the `AxiosPromise` in a `HubSpotPromise` type and exports it so that integrators don't need to use `ReturnType` annotations to have access to the type.
> fix!: Wrap Axios type and export new type

- package.json
- types/MarketplaceValidation.ts
This makes a few updates to types used by the `hs module marketplace-validation` command and related endpoints.
* Exports the `Check` type
* Updates the `errors` field on `GetValidationResultsResponse` (see [API catalog ](https://tools.hubteam.com/api-catalog/services/QualityEngineService/v1/spec/internal#operations-Validation-get-%2Fquality-engine%2Fv1%2Fvalidation%2Fresults)for this endpoint
> chore: Update validation types

- api/github.ts
- lib/github.ts
- types/developerTestAccounts.ts
Is a dependency of: https://github.com/HubSpot/hubspot-cli/pull/1288
As part of our work to convert the CLI to TypeScript, we're typing prompts that rely on downloading content from GitHub. We were mistakenly returning the `Buffer` type from the `fetchFileFromRepository` function. In fact, this function returns the contents of the file (`resp.data`) we're downloading. Since literally anything can be in a file downloaded from GitHub, this is an instance of a true `any` type, in my opinion.
@camden11 @brandenrodgers @joe-yeager
> chore: Refactor types for fetching GitHub content

- types/Accounts.ts
The type for auth was missing `clientId` and `clientSecret`. This was causing issues over in the CLI.
> Chore: Fixing type for the auth field in the config

- api/projects.ts
- package.json
- types/Build.ts
- types/Deploy.ts
- types/Error.ts
- types/Migration.ts
- types/Project.ts
This fixes a few inaccuracies with types related to projects + removes the `OptionalError` types which is no longer needed.
Type changes based on API responses herer: https://tools.hubteam.com/api-catalog/services/DFSBuildPipelineService/v1/spec/internal
@brandenrodgers @joe-yeager @kemmerle
> Chore: update project types

- config/config_DEPRECATED.ts
https://github.com/HubSpot/hubspot-cli/pull/1307 relies on this PR.
While we were porting it to TypeScript, we made a change in the deprecated config, so that on creation, the config contains a `portals` property set to an empty array (`{ portals: [] }`). This means that we need to refactor our error handling in config validation to handle cases where `portals` is set to an empty array.
> Add error case in deprecated config

- types/Accounts.ts
I missed the auth type in the deprecated config in https://github.com/HubSpot/hubspot-local-dev-lib/pull/220. We also need to fix it here.
> Fix auth type for deprecated config

- api/__tests__/projects.test.ts
- api/projects.ts
- lib/fs.ts
- types/Project.ts
Update the `uploadProject` method to accept the IR.
Optimize the `walk` method to ignore provided ignore directories
> feat: Update uploadProject method to support IR.  Optimize walk method

- api/functions.ts
- types/Functions.ts
These types were missing for some reason, but the CLI relies on them.
Pulled from here: https://tools.hubteam.com/api-catalog/services/ContentServerlessFunctionsService/v3/spec/internal
> Add types for CMS function logs API responses

- lib/__tests__/functions.test.ts
- lib/__tests__/templates.test.ts
- lib/cms/functions.ts
- lib/cms/modules.ts
- lib/cms/templates.ts
- lib/github.ts
Changes made:
- Deprecate `downloadGithubRepoContents` because it is inefficient and tends to hit rate limits
- Replace `downloadGithubRepoContents` with `cloneGithubRepo` to optimize the number of calls to GitHub
- Make any required tweaks to account for the transition
> fix: Move GitHub downloads to optimized method

- api/localDevAuth.ts
- lib/personalAccessKey.ts
- types/Accounts.ts
Adds various models so we can fetch scope authorization data for use in the CLI when debugging potential local dev issues.
Subsequent PR incoming in [HubSpot/hubspot-cli](https://github.com/HubSpot/hubspot-cli/) and will link accordingly.
> feat: add fixtures to fetch scope authorization data per portal and user

- config/index.ts
This was manifesting itself in the `hs account rename` command in the CLI. These async functions weren't returning a promise, so there was nothing to `await` for in the CLI code. This meant that the errors thrown by these utils would never get caught by any try/catch block in the CLI.
You can see the impact of this by running `hs account rename blah-blah some-gibberish`
> Return promises from async functions

- package.json
Noticed that we were still using the `main` field in `package.json` to specify an entry point file that doesn't exist. `exports` replaces `main` so we can remove this
> Chore: Remove main field from package.json

- lib/github.ts
- types/Github.ts
This adds a `hideLogs` option to the GH download util that prevents it from logging anything to the console. The CLI will leverage this for the project-related downloads, where we can provide our own logs from the CLI side.
This also deprecates the thin wrapper around fetchRepoFile
> Add hide logs option to GH download util

- config/index.ts
This PR adds functions that support refactoring the `hs account` bucket to account for `.hsaccount` override files with the new config. 
See https://github.com/HubSpot/hubspot-cli/pull/1407
> Support `hs account` bucket refactor

- config/migrate.ts
This impacts the migration flow for global config. I was using the `Boolean(config_DEPRECATED.loadConfig(configPath))` function in the `configFileExists` function to check whether the deprecated config exists. The deprecated config function is working as designed and throws an error that says `A hubspot.config.yml file could not be found. To create a new config file, use the "hs init" command.` But we don't need that error with global config, and it might lead to confusion with customers.
I've replaced that function with `config_DEPRECATED.getConfigPath(configPath)`. As @camden11 pointed out, however, when a `configPath` is provided as argument, the function simply returns it. I've protected against that by checking whether the config path exists before running the command.  
BEFORE …
> Fix migration bug p2

- models/HubSpotHttpError.ts
This adds the `timeout` field from `AxiosError` to `HubSpotHttpError`, so that the CLI can check it and determine if timeouts were caused by the config default timeout.
@brandenrodgers @joe-yeager @kemmerle
> Add timeout to HubSpotHttpError

- config/__tests__/migrate.test.ts
- config/migrate.ts
- lang/en.json
In an attempt to not let the config revamp work get too stale, I've updated the `dynamic-config` branch to apply the new config logic to @kemmerle's migration work. The fact that the global and deprecated config are both converted to the same object shape makes merging them much simpler. Like the rest of the config revamp work, this will be breaking for the CLI, but we'll cross that bridge when we get there
Note: merging this into my `dynamic-config` branch, not main
@kemmerle @brandenrodgers @joe-yeager
> Dynamic config migrations

- models/HubSpotHttpError.ts
Fixes a runtime issue when `response.data` is html
> fix: make sure response.data is an object before using `in` operator

- api/developerTestAccounts.ts
- types/developerTestAccounts.ts
The return type isn't the same as the dev test account shape. It includes a personal access key that we can immediately store in the CLI config. This prevents us from having to prompt the user for the key after creating the account.
> Fix the return type of the create dev test account api

- http/index.ts
Add a few more fields to the logging.  Use util.inspect to expand the full object in the logs.  
Example output:
```
[DEBUG] {
method: 'get',
baseURL: 'https://api.hubspotqa.com',
url: 'dfs/logging/v1/logs/projects/meme-generator-v2/deploys/1044/combined/warn',
data: { logs: [] },
status: 200
}
```
> chore: Add more fields to network logging, use util inspect

- lib/__tests__/text.test.ts
- lib/text.ts
Check if the string is defined before calling `str.replace`
> fix: Check if string is defined before attempting to access string methods

- models/HubSpotHttpError.ts
Fixes an issue when the upload endpoint sometimes returns a `string` instead an array of `ErrorDetails`
> fix: Check if errors is an array before attempting to iterate it

- lib/cms/handleFieldsJS.ts
I'm porting `cms convert-fields` to TS and ran into a type issue. All the commands take `fieldOptions` as an array of strings.
I checked what it was back in cli-lib and it looks like it was an array there too: https://github.com/HubSpot/cli-lib/blob/main/lib/handleFieldsJs.js#L22
> Fix field options type

- lib/cms/modules.ts
This function is kind of odd. It returns void if you pass a name and dest, and it returns a list of github files if you pass it nothing. I added an overload to it so the return type is more useful. This is helpful in the `cms get-react-module` command in the CLI
> Add override for retrieveDefaultModule

- config/CLIConfiguration.ts
- config/__tests__/config.test.ts
- config/config_DEPRECATED.ts
The DevRel team discovered a bug, where they could not name accounts numbers, (ie. `2024`, `57`, etc). This was because we were using a regular expression to check with the `nameOrId` was a number--if it was, we then converted it to a number and treated it as the account ID. Now that we've implemented TypeScript in LDL and the CLI, we no longer need to perform this kind of check. We always know that the account name will be a string and the account ID is a number. 
Before:
After:
> Fix: Account names cannot be numbers

- lib/__tests__/archive.test.ts
- lib/archive.ts
- lib/github.ts
- types/Archive.ts
- types/Github.ts
Update `extractZipArchive` method to take a array of `sourceDir` and copy all of the locations to the destination directoy.
> feat: Support extracting multiple `sourceDir` locations in `extractZipArchive`

- api/appsDev.ts
This adds a new function to hit `apps-hublets/external/static-token/v3`, which is used to install static auth apps in test accounts. This will be used in `hs project dev`.
@brandenrodgers @joe-yeager
> Add endpoint to install static auth apps on test accounts

- config/CLIConfiguration.ts
- config/__tests__/config.test.ts
- config/config_DEPRECATED.ts
- config/index.ts
- lang/en.json
- types/Config.ts
This adds a new config setting/flag `autoOpenLocalDevSessionInBrowser`. This will be used by the CLI to allow users to prevent Local Dev UI from opening automatically when they run `hs project dev`
@brandenrodgers @joe-yeager @lkosarpersonal
> Add autoOpenLocalDevSessionInBrowser option to config

- lib/__tests__/uploadFolder.test.ts
- lib/cms/uploadFolder.ts
- package.json
- utils/cms/modules.ts
- Upload new module meta.json files sequentially before other files in order to ensure that the module's meta information set locally is persisted correctly when it makes to the creation process and BE model generation.
There is a current bug where, when a customer uploads files from their local development, the module_id and other properties are not actually being set correctly if the module is net-new. So, a customer working with version control, or fetching those modules back down, will see incorrect information in the meta.json including the `module_id` property -- which is set dynamically on the BE if not present in the meta.json (something it can check for prematurely to the local meta.json actually being processed).
This PR pushed meta.json files into their own queue and batch …
> Ensure newly uploaded module at /path have their meta.json files uploaded first

- api/appsDev.ts
This adds a function for the new `apps-dev/external/public/v3/full/portal/sourceId` to LDL. This endpoint allows the CLI to fetch app metadata directly by UID, which is much faster than the previous setup, where it had to fetch _every_ app in a users portal and then filter by UID. This will be used to speed up `hs project dev`
@brandenrodgers @joe-yeager @chiragchadha1
> Add endpoint to get app by UID
